### ISSUE TITLE
installation instructions and demo ?

### ISSUE THREAD

**Issue by vesper8** [dhedegaard/youtube#104]
Hi there! Your project seems interesting to me and it's nice to see you're still keeping it up-to-date years later!

Is there a demo somewhere by any chance, or a live website that makes use of this?

Also, any chance you could provide some quick and dirty installation instructions? I see I have to add the API key in the settings.py file, but what about other things like creating a database and where do I input the rest of the configuration parameters?

Thanks much!

**Comment by dhedegaard** [comment]
Hi vesper,

thanks for your interest in the project.

I've tried to answer your questions by writing a better [README](https://github.com/dhedegaard/youtube).

Take a look and let me know if you have more questions 😉

**Comment by vesper8** [comment]
thank you @dhedegaard ! that's so much clearer!

I'll check it out when I get back home later.

One question though.. what is the purpose of this app in its current state?

Do you have to add the channels manually or does it somehow fetch the logged-in user's favourite channels ? 

Is it supposed to be a system where any user can register and then start adding channels to their own personal feed?

**Comment by dhedegaard** [comment]
Hi @vesper8 

It's really just a site for listing the newest videos from various youtube channels.

I got annoyed by not being able to get a list of the latests videos from youtube.com itself.

You add the channels manually.

For now there's no logic for letting users create their own accounts, but it shouldn't be too hard to implement.
