### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by simracingstudio** [dhedegaard/youtube#117]

**Comment by dhedegaard** [comment]
Hi @simracingstudio 

I've added a LICENSE file to the project, GPL v3.

Why do you ask?

**Comment by simracingstudio** [comment]
I was planning to use it with a closed source project.
Unfortunately GPL would not work for us.
LGPL or MIT would.
Good job on this BTW.
Get Outlook for Android

**Comment by dhedegaard** [comment]
@simracingstudio sorry to disappoint. Closing the issue.
